# Generated by Django 4.1 on 2022-08-28 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Раздел витрины')),
                ('description', models.CharField(max_length=100, verbose_name='Описание раздела витрины')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название товара')),
                ('description', models.TextField(max_length=500, verbose_name='Описание товара')),
                ('image', models.ImageField(upload_to='products/images/', verbose_name='Изображение товара')),
                ('price', models.FloatField(default=0, verbose_name='Цена товара')),
                ('quantity', models.IntegerField(default=0, verbose_name='Количество на складе')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='backend.section', verbose_name='Раздел товара')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ('name',),
            },
        ),
    ]
